name: Check if Work Item is completed

on:
  [push]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  check-issues:
    runs-on: ubuntu-latest
    steps:
      - name: List Issues
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });

            console.log(issues[0].body)
